 #@ load("@ytt:data", "data")

apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: tcp
spec:
  params:
  - default: main
    name: gitops_branch
  - default: supplychain
    name: gitops_user_name
  - default: supplychain
    name: gitops_user_email
  - default: supplychain@cluster.local
    name: gitops_commit_message
  - default: #@ data.values.gitops_secret
    name: gitops_ssh_secret
  - default:
    - containerPort: 8080
      port: 8080
      name: http
    name: ports
  resources:
  - name: source-provider
    params:
    - name: serviceAccount
      value: default
    - name: gitImplementation
      value: go-git
    templateRef:
      kind: ClusterSourceTemplate
      name: source-template
  - name: deliverable
    params:
    - name: registry
      value:
        repository: #@ data.values.registry_repo
        server: #@ data.values.registry_server
    templateRef:
      kind: ClusterTemplate
      name: deliverable-template
  - name: image-builder
    params:
    - name: serviceAccount
      value: default
    - name: clusterBuilder
      value: default
    - name: registry
      value:
        repository: #@ data.values.registry_repo
        server: #@ data.values.registry_server
    sources:
    - name: source
      resource: source-provider
    templateRef:
      kind: ClusterImageTemplate
      name: kpack-template
  - images:
    - name: image
      resource: image-builder
    name: config-provider
    params:
    - name: serviceAccount
      value: default
    templateRef:
      kind: ClusterConfigTemplate
      name: convention-template
  - configs:
    - name: config
      resource: config-provider
    name: app-config
    templateRef:
      kind: ClusterConfigTemplate
      name: deployment-and-service-template
  - configs:
    - name: app_def
      resource: app-config
    name: apply-bindings
    templateRef:
      kind: ClusterConfigTemplate
      name: apply-bindings
  - configs:
    - name: config
      resource: apply-bindings
    name: config-writer
    params:
    - name: serviceAccount
      value: default
    - name: registry
      value:
        repository: #@ data.values.registry_repo
        server: #@ data.values.registry_server
    templateRef:
      kind: ClusterTemplate
      name: config-writer-template
  selector:
    apps.tanzu.vmware.com/workload-type: tcp
---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: queue
spec:
  params:
  - default: main
    name: gitops_branch
  - default: supplychain
    name: gitops_user_name
  - default: supplychain
    name: gitops_user_email
  - default: supplychain@cluster.local
    name: gitops_commit_message
  - default: #@ data.values.gitops_secret
    name: gitops_ssh_secret
  resources:
  - name: source-provider
    params:
    - name: serviceAccount
      value: default
    - name: gitImplementation
      value: go-git
    templateRef:
      kind: ClusterSourceTemplate
      name: source-template
  - name: deliverable
    params:
    - name: registry
      value:
        repository: #@ data.values.registry_repo
        server: #@ data.values.registry_server
    templateRef:
      kind: ClusterTemplate
      name: deliverable-template
  - name: image-builder
    params:
    - name: serviceAccount
      value: default
    - name: clusterBuilder
      value: default
    - name: registry
      value:
        repository: #@ data.values.registry_repo
        server: #@ data.values.registry_server
    sources:
    - name: source
      resource: source-provider
    templateRef:
      kind: ClusterImageTemplate
      name: kpack-template
  - images:
    - name: image
      resource: image-builder
    name: config-provider
    params:
    - name: serviceAccount
      value: default
    templateRef:
      kind: ClusterConfigTemplate
      name: convention-template
  - configs:
    - name: config
      resource: config-provider
    name: app-config
    templateRef:
      kind: ClusterConfigTemplate
      name: deployment-template
  - configs:
    - name: app_def
      resource: app-config
    name: apply-bindings
    templateRef:
      kind: ClusterConfigTemplate
      name: apply-bindings
  - configs:
    - name: config
      resource: apply-bindings
    name: config-writer
    params:
    - name: serviceAccount
      value: default
    - name: registry
      value:
        repository: #@ data.values.registry_repo
        server: #@ data.values.registry_server
    templateRef:
      kind: ClusterTemplate
      name: config-writer-template
  selector:
    apps.tanzu.vmware.com/workload-type: queue
